# Require the AWS provider plugin
require 'vagrant-aws'

instance = "mbl2019-instructor"
project = "mbl2019"
poc = "mblneuro2017@gmail.com"

# Create and configure the AWS instance(s)
Vagrant.configure('2') do |config|

  # Use dummy AWS box
  config.vm.box = 'dummy'
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  # Specify AWS provider configuration
  config.vm.provider 'aws' do |aws, override|

    # Specify SSH keypair to use
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name = ENV['AWS_KEYNAME']
    aws.security_groups = ["sg-053122e8f057157af"]  # MBL only
    aws.elastic_ip = '34.204.46.183'
    aws.iam_instance_profile_name = "EC2ReadWriteDataBucket"
    # Specify region, AMI ID, and security group(s)
    aws.region = 'us-east-1'
    aws.elastic_ip = '3.216.168.152'
    aws.ami = 'ami-0efc465abe109426c' #MBL_v1: ami-0efc465abe109426c
    aws.instance_type = 'm4.large' # 't2.2xlarge'
    aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 100, 'Ebs.VolumeType' => 'gp2' }]
    aws.subnet_id = 'subnet-3a46bf60'
    aws.associate_public_ip = true
    aws.terminate_on_shutdown = true

    # Specify username and private key path
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    # Reminder: connect to RStudio server at port 80, webserver at port 8080
    #   username: ubuntu (or others set up in bootstrap.sh)
    #   password: bioc
    
    # Tags
    aws.tags = {
      'Name' => "#{instance}",
      'env' => 'dev',
      'project' => "#{project}",
      'poc' => "#{poc}"
    }

    # Boostrapping
    aws.user_data = File.read("bootstrap.sh")

  end
end
