# Require the AWS provider plugin
require 'vagrant-aws'

instance = "mbl2019-instance"
project = "mbl2019"
poc = "mblneuro2017@gmail.com"

# Create and configure the AWS instance(s)
Vagrant.configure('2') do |config|
  
  # Use dummy AWS box
  config.vm.box = 'dummy'
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  # Specify AWS provider configuration
  config.vm.provider 'aws' do |aws, override|

    # Specify SSH keypair to use
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name = ENV['AWS_KEYNAME']
    aws.security_groups = ["sg-fe751980"]  # open to the world
    aws.iam_instance_profile_name = "EC2ReadWriteDataBucket"
    # Specify region, AMI ID, and security group(s)
    aws.region = 'us-east-1'
    aws.ami = 'ami-08333c98cd3b5ada7' # BioC 3.9 
    aws.instance_type = 't2.small'
    aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 50 }]
    aws.subnet_id = 'subnet-3a46bf60'
    aws.associate_public_ip = true
    aws.terminate_on_shutdown = true

    # Specify username and private key path
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    # Reminder: connect to RStudio server at port 80
    #   username: ubuntu (or others set up in bootstrap.sh)
    #   password: bioc
    
    # Tags
    aws.tags = {
      'Name' => "#{instance}",
      'env' => 'dev',
      'project' => "#{project}",
      'poc' => "#{poc}"
    }

    # Boostrapping
    aws.user_data = File.read("bootstrap.sh")

  end
end
