# Require the AWS provider plugin and YAML module
require 'vagrant-aws'
require 'yaml'
project = "mbl2018"
poc = "mblneuro2017@gmail.com"

# Read YAML file with instance information
instances = YAML.load_file(File.join(File.dirname(__FILE__), 'instances.yml'))

# Specify Vagrant version and Vagrant API version
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

# Create and configure the AWS instance(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Use dummy AWS box
  config.vm.box = 'dummy'
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  # Configure default AWS provider settings
  config.vm.provider 'aws' do |aws|

    # Specify access/authentication information
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    # Specify default AWS key pair
    aws.keypair_name = "participant"

    # Specify default region and default AMI ID
    aws.region = 'us-east-1'
    aws.user_data = File.read("bootstrap.sh")

  end # config.vm.provider 'aws'

  # Loop through YAML file and set per-instance information
  instances.each do |instance|
    config.vm.define instance['name'] do |srv|

      # Disable default shared folder
      srv.vm.synced_folder '.', '/vagrant', disabled: true

      # Set per-instance provider configuration/overrides
      srv.vm.provider 'aws' do |aws, override|
        override.ssh.private_key_path = '/Users/sandmann/.ssh/participant.pem'
        override.ssh.username = instance['user']
        aws.instance_type = instance['type']
        aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1',
                                      'Ebs.VolumeSize' => 100,
                                      'Ebs.VolumeType' => 'gp2' }]
        aws.ami = instance['ami']
        aws.security_groups = ["sg-fe751980"]
        aws.iam_instance_profile_name = "EC2ReadDataBucket"
        aws.subnet_id = 'subnet-3a46bf60'
        aws.elastic_ip = instance['ip']
        aws.tags = {
          'Name' => instance['name'],
          'env' => 'dev',
          'project' => "#{project}",
          'poc' => "#{poc}"
        }
      
      end # srv.vm.provider 'aws'
    end # config.vm.define
  end # instances.each
end # Vagrant.configure
